import { Inter } from "next/font/google";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import StoreProvider from "./StoreProvider";
import "./globals.css";
import DefaultLocalStorage from "@/components/default-localStorage/DefaultLocalStorage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Header />
          <main className="max-w-[1920px] mx-auto">{children}</main>
          <DefaultLocalStorage />
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
